//AUTH ACTIONS

export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_ERROR = 'LOGIN_ERROR' 
export const LOGOUT_SUCCESSFULL = 'LOGOUT_SUCCESSFULL'


export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED'


export const LOGIN_WITH_GOOGLE_SUCCESSFULL = 'LOGIN_WITH_GOOGLE_SUCCESSFULL';
export const LOGIN_WITH_GOOGLE_FAILED = 'LOGIN_WITH_GOOGLE_FAILED'  

export const LOGIN_WITH_FB_SUCCESSFULL = 'LOGIN_WITH_FB_SUCCESSFULL'
export const LOGIN_WITH_FB_FAILED = 'LOGIN_WITH_FB_FAILED' 


export const TOAST_REMOVER = 'TOAST_REMOVER';



//QUANTITY REDUCER

export const ADD_TICKET = 'ADD_TICKET';

export const DELETE_TICKET = 'DELETE_TICKET';

export const REMOVE_TICKET = "REMOVE_TICKET"